### ISSUE TITLE
cannot build on linux - conceal-wallet/src/gui/nodesettings.cpp:9:10: fatal error: NodeSettings.h: No such file or directory

### ISSUE THREAD

**Issue by stanec** [ConcealNetwork/conceal-wallet#45]
Following official building instructions I got this (Fedora linux, up to now I had no issues with older version):

[root@rs conceal-wallet]# make build-release
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /root/conceal-wallet/build/release
cd build/release && make
make[1]: Entering directory '/root/conceal-wallet/build/release'
make[2]: Entering directory '/root/conceal-wallet/build/release'
make[3]: Entering directory '/root/conceal-wallet/build/release'
Scanning dependencies of target cryptonote_autogen
make[3]: Leaving directory '/root/conceal-wallet/build/release'
make[3]: Entering directory '/root/conceal-wallet/build/release'
[  0%] Automatic MOC for target cryptonote
make[3]: Leaving directory '/root/conceal-wallet/build/release'
[  0%] Built target cryptonote_autogen
make[3]: Entering directory '/root/conceal-wallet/build/release'
Scanning dependencies of target cryptonote
make[3]: Leaving directory '/root/conceal-wallet/build/release'
make[3]: Entering directory '/root/conceal-wallet/build/release'
[  1%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/connecthostport.c.o
[  1%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/igd_desc_parse.c.o
[  1%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/minisoap.c.o
[  2%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/miniupnpc.c.o
[  2%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/miniwget.c.o
[  3%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/minixml.c.o
[  3%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/portlistingparse.c.o
[  3%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/receivedata.c.o
[  4%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/upnpcommands.c.o
[  4%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/upnpreplyparse.c.o
[  5%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/Base58.cpp.o
[  5%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/CommandLine.cpp.o
[  5%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/Util.cpp.o
[  6%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/StringTools.cpp.o
[  6%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/JsonValue.cpp.o
[  7%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/ConsoleTools.cpp.o
[  7%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/MemoryInputStream.cpp.o
[  8%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/PathTools.cpp.o
[  8%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/DnsTools.cpp.o
[  8%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/StdInputStream.cpp.o
[  9%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/StdOutputStream.cpp.o
[  9%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/StreamTools.cpp.o
[ 10%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/StringOutputStream.cpp.o
[ 10%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/StringView.cpp.o
[ 10%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Common/VectorOutputStream.cpp.o
[ 11%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/aux_hash.c.o
[ 11%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/chacha.c.o
[ 12%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/chacha8.c.o
[ 12%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/crypto-ops-data.c.o
[ 12%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/crypto-ops.c.o
[ 13%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/crypto.cpp.o
[ 13%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/hash.c.o
[ 14%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/cryptonight.cpp.o
[ 14%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/keccak.c.o
[ 14%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/random.c.o
[ 15%] Building C object CMakeFiles/cryptonote.dir/cryptonote/src/crypto/tree-hash.c.o
[ 15%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/BlockchainIndices.cpp.o
[ 16%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/BlockchainMessages.cpp.o
[ 16%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/BlockIndex.cpp.o
[ 16%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/CoreConfig.cpp.o
[ 17%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/CryptoNoteBasic.cpp.o
[ 17%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/CryptoNoteTools.cpp.o
[ 18%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Currency.cpp.o
[ 18%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/DepositIndex.cpp.o
[ 18%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/InvestmentIndex.cpp.o
[ 19%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/MinerConfig.cpp.o
[ 19%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Transaction.cpp.o
[ 20%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Account.cpp.o
[ 20%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Blockchain.cpp.o
[ 20%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Checkpoints.cpp.o
[ 21%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/CryptoNoteBasicImpl.cpp.o
[ 21%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Core.cpp.o
[ 22%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/CryptoNoteFormatUtils.cpp.o
[ 22%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/CryptoNoteSerialization.cpp.o
[ 22%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Difficulty.cpp.o
[ 23%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/IBlock.cpp.o
[ 23%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/Miner.cpp.o
[ 24%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/TransactionExtra.cpp.o
[ 24%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/TransactionPool.cpp.o
[ 25%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/TransactionPrefixImpl.cpp.o
[ 25%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteCore/TransactionUtils.cpp.o
[ 25%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/InProcessNode/InProcessNode.cpp.o
[ 26%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/InProcessNode/InProcessNodeErrors.cpp.o
[ 26%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/NodeRpcProxy/NodeErrors.cpp.o
[ 27%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/NodeRpcProxy/NodeRpcProxy.cpp.o
[ 27%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/P2p/NetNodeConfig.cpp.o
[ 27%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/BinaryInputStreamSerializer.cpp.o
[ 28%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/BinaryOutputStreamSerializer.cpp.o
[ 28%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/JsonInputValueSerializer.cpp.o
[ 29%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/JsonOutputStreamSerializer.cpp.o
[ 29%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/KVBinaryInputStreamSerializer.cpp.o
[ 29%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/KVBinaryOutputStreamSerializer.cpp.o
[ 30%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Serialization/SerializationOverloads.cpp.o
[ 30%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Transfers/BlockchainSynchronizer.cpp.o
[ 31%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Transfers/SynchronizationState.cpp.o
[ 31%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Transfers/TransfersConsumer.cpp.o
[ 31%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Transfers/TransfersContainer.cpp.o
[ 32%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Transfers/TransfersSubscription.cpp.o
[ 32%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Transfers/TransfersSynchronizer.cpp.o
[ 33%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Wallet/LegacyKeysImporter.cpp.o
[ 33%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Wallet/WalletAsyncContextCounter.cpp.o
[ 33%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Wallet/WalletErrors.cpp.o
[ 34%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/KeysStorage.cpp.o
[ 34%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletLegacy.cpp.o
[ 35%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletHelper.cpp.o
[ 35%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletLegacySerializer.cpp.o
[ 35%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletLegacySerialization.cpp.o
[ 36%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletTransactionSender.cpp.o
[ 36%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletUnconfirmedTransactions.cpp.o
[ 37%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/WalletLegacy/WalletUserTransactionsCache.cpp.o
[ 37%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/System/ContextGroup.cpp.o
[ 37%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/System/Event.cpp.o
[ 38%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/System/EventLock.cpp.o
[ 38%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/System/InterruptedException.cpp.o
[ 39%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/System/Ipv4Address.cpp.o
[ 39%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/System/TcpStream.cpp.o
[ 39%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/HTTP/HttpRequest.cpp.o
[ 40%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/HTTP/HttpParser.cpp.o
[ 40%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/HTTP/HttpParserErrorCodes.cpp.o
[ 41%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/HTTP/HttpResponse.cpp.o
[ 41%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Rpc/HttpClient.cpp.o
[ 42%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Rpc/JsonRpc.cpp.o
[ 42%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/P2p/NetNode.cpp.o
[ 42%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/P2p/LevinProtocol.cpp.o
[ 43%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/P2p/PeerListManager.cpp.o
[ 43%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp.o
[ 44%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/ILogger.cpp.o
[ 44%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/LoggerGroup.cpp.o
[ 44%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/CommonLogger.cpp.o
[ 45%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/LoggerManager.cpp.o
[ 45%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/FileLogger.cpp.o
[ 46%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/StreamLogger.cpp.o
[ 46%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/ConsoleLogger.cpp.o
[ 46%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/LoggerMessage.cpp.o
[ 47%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Logging/LoggerRef.cpp.o
[ 47%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/BlockchainExplorer/BlockchainExplorer.cpp.o
[ 48%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/BlockchainExplorer/BlockchainExplorerDataBuilder.cpp.o
[ 48%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/BlockchainExplorer/BlockchainExplorerErrors.cpp.o
[ 48%] Building C object CMakeFiles/cryptonote.dir/cryptonote/external/miniupnpc/minissdpc.c.o
[ 49%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/Dispatcher.cpp.o
[ 49%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/ErrorMessage.cpp.o
[ 50%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/Ipv4Resolver.cpp.o
[ 50%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/TcpConnection.cpp.o
[ 50%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/TcpConnector.cpp.o
[ 51%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/TcpListener.cpp.o
[ 51%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote/src/Platform/Linux/System/Timer.cpp.o
[ 52%] Building CXX object CMakeFiles/cryptonote.dir/cryptonote_autogen/mocs_compilation.cpp.o
[ 52%] Linking CXX static library libcryptonote.a
make[3]: Leaving directory '/root/conceal-wallet/build/release'
[ 52%] Built target cryptonote
make[3]: Entering directory '/root/conceal-wallet/build/release'
Scanning dependencies of target qrencode
make[3]: Leaving directory '/root/conceal-wallet/build/release'
make[3]: Entering directory '/root/conceal-wallet/build/release'
[ 53%] Building C object CMakeFiles/qrencode.dir/libqrencode/bitstream.c.o
[ 53%] Building C object CMakeFiles/qrencode.dir/libqrencode/mask.c.o
[ 54%] Building C object CMakeFiles/qrencode.dir/libqrencode/mmask.c.o
[ 54%] Building C object CMakeFiles/qrencode.dir/libqrencode/mqrspec.c.o
[ 54%] Building C object CMakeFiles/qrencode.dir/libqrencode/qrencode.c.o
[ 55%] Building C object CMakeFiles/qrencode.dir/libqrencode/qrinput.c.o
[ 55%] Building C object CMakeFiles/qrencode.dir/libqrencode/qrspec.c.o
[ 56%] Building C object CMakeFiles/qrencode.dir/libqrencode/rscode.c.o
[ 56%] Building C object CMakeFiles/qrencode.dir/libqrencode/split.c.o
[ 57%] Linking C static library libqrencode.a
make[3]: Leaving directory '/root/conceal-wallet/build/release'
[ 57%] Built target qrencode
make[3]: Entering directory '/root/conceal-wallet/build/release'
Scanning dependencies of target CONCEAL-GUI_autogen
make[3]: Leaving directory '/root/conceal-wallet/build/release'
make[3]: Entering directory '/root/conceal-wallet/build/release'
[ 57%] Automatic MOC for target CONCEAL-GUI
make[3]: Leaving directory '/root/conceal-wallet/build/release'
[ 57%] Built target CONCEAL-GUI_autogen
make[3]: Entering directory '/root/conceal-wallet/build/release'
[ 57%] Generating qrc_resources.cpp
/root/conceal-wallet/src/resources.qrc: Warning: potential duplicate alias detected: 'Lato-Regular.ttf'
[ 57%] Generating ui_aboutdialog.h
[ 57%] Generating ui_addressbookdialog.h
[ 58%] Generating ui_addressbookframe.h
[ 58%] Generating ui_changepassworddialog.h
[ 59%] Generating ui_depositdetailsdialog.h
[ 59%] Generating ui_depositsframe.h
[ 59%] Generating ui_disclaimerdialog.h
[ 60%] Generating ui_exitwidget.h
[ 60%] Generating ui_importkeydialog.h
[ 61%] Generating ui_importsecretkeys.h
[ 61%] Generating ui_importseed.h
[ 61%] Generating ui_importtracking.h
[ 62%] Generating ui_importviewkey.h
[ 62%] Generating ui_linksdialog.h
[ 63%] Generating ui_mainwindow.h
[ 63%] Generating ui_messageaddressframe.h
[ 63%] Generating ui_messagedetailsdialog.h
[ 64%] Generating ui_messagesframe.h
[ 64%] Generating ui_miningframe.h
[ 65%] Generating ui_newaddressdialog.h
[ 65%] Generating ui_newnodedialog.h
[ 65%] Generating ui_newpassworddialog.h
[ 66%] Generating ui_newpooldialog.h
[ 66%] Generating ui_nodesettings.h
[ 67%] Generating ui_overviewframe.h
[ 67%] Generating ui_passworddialog.h
[ 67%] Generating ui_receiveframe.h
[ 68%] Generating ui_sendframe.h
[ 68%] Generating ui_sendmessageframe.h
[ 69%] Generating ui_showqrcode.h
[ 69%] Generating ui_transactionconfirmation.h
[ 69%] Generating ui_transactiondetailsdialog.h
[ 70%] Generating ui_transactionframe.h
[ 70%] Generating ui_transactionsframe.h
[ 71%] Generating ui_transferframe.h
[ 71%] Generating ui_welcomeframe.h
Scanning dependencies of target CONCEAL-GUI
make[3]: Leaving directory '/root/conceal-wallet/build/release'
make[3]: Entering directory '/root/conceal-wallet/build/release'
[ 72%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/AddressProvider.cpp.o
[ 72%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/AliasProvider.cpp.o
[ 73%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/CommandLineParser.cpp.o
[ 73%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/CryptoNoteWrapper.cpp.o
[ 74%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/CurrencyAdapter.cpp.o
[ 74%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/LoggerAdapter.cpp.o
[ 74%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/NodeAdapter.cpp.o
[ 75%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/PriceProvider.cpp.o
[ 75%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/Settings.cpp.o
[ 76%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/SignalHandler.cpp.o
[ 76%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/StratumClient.cpp.o
[ 76%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/Update.cpp.o
[ 77%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/WalletAdapter.cpp.o
[ 77%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/Worker.cpp.o
[ 78%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/AboutDialog.cpp.o
[ 78%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/AddressBookDialog.cpp.o
[ 78%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/AddressBookFrame.cpp.o
[ 79%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/AddressBookModel.cpp.o
[ 79%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/AddressListModel.cpp.o
[ 80%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/AnimatedLabel.cpp.o
[ 80%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/ChangePasswordDialog.cpp.o
[ 80%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/DepositDetailsDialog.cpp.o
[ 81%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/DepositListModel.cpp.o
[ 81%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/DepositModel.cpp.o
[ 82%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/DepositsFrame.cpp.o
[ 82%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/DisclaimerDialog.cpp.o
[ 82%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/ExitWidget.cpp.o
[ 83%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/ImportKeyDialog.cpp.o
[ 83%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/LinksDialog.cpp.o
[ 84%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/MainWindow.cpp.o
[ 84%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/Message.cpp.o
[ 84%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/MessageAddressFrame.cpp.o
[ 85%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/MessageDetailsDialog.cpp.o
[ 85%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/MessagesFrame.cpp.o
[ 86%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/MessagesModel.cpp.o
[ 86%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/NewAddressDialog.cpp.o
[ 86%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/NewNodeDialog.cpp.o
[ 87%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/NewPasswordDialog.cpp.o
[ 87%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/NewPoolDialog.cpp.o
[ 88%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/NodeModel.cpp.o
[ 88%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/OverviewFrame.cpp.o
[ 88%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/PasswordDialog.cpp.o
[ 89%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/PoolModel.cpp.o
[ 89%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/QRLabel.cpp.o
[ 90%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/ReceiveFrame.cpp.o
[ 90%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/RecentTransactionsModel.cpp.o
[ 91%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/SendFrame.cpp.o
[ 91%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/SendMessageFrame.cpp.o
[ 91%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/ShowQRCode.cpp.o
[ 92%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/SortedAddressListModel.cpp.o
[ 92%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/SortedDepositModel.cpp.o
[ 93%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/SortedMessagesModel.cpp.o
[ 93%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/SortedTransactionsModel.cpp.o
[ 93%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/TransactionDetailsDialog.cpp.o
[ 94%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/TransactionFrame.cpp.o
[ 94%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/TransactionsFrame.cpp.o
[ 95%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/TransactionsListModel.cpp.o
[ 95%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/TransactionsModel.cpp.o
[ 95%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/TransferFrame.cpp.o
[ 96%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/VisibleMessagesModel.cpp.o
[ 96%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/WelcomeFrame.cpp.o
[ 97%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/importsecretkeys.cpp.o
[ 97%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/importseed.cpp.o
[ 97%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/importtracking.cpp.o
[ 98%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/nodesettings.cpp.o
/root/conceal-wallet/src/gui/nodesettings.cpp:9:10: fatal error: NodeSettings.h: No such file or directory
 #include "NodeSettings.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/CONCEAL-GUI.dir/build.make:1084: CMakeFiles/CONCEAL-GUI.dir/src/gui/nodesettings.cpp.o] Error 1
make[3]: Leaving directory '/root/conceal-wallet/build/release'
make[2]: *** [CMakeFiles/Makefile2:144: CMakeFiles/CONCEAL-GUI.dir/all] Error 2
make[2]: Leaving directory '/root/conceal-wallet/build/release'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/root/conceal-wallet/build/release'
make: *** [Makefile:20: build-release] Error 2

**Comment by krypt0x** [comment]
It seems there is a file missing. 

```C
[ 98%] Building CXX object CMakeFiles/CONCEAL-GUI.dir/src/gui/nodesettings.cpp.o
/root/conceal-wallet/src/gui/nodesettings.cpp:9:10: fatal error: NodeSettings.h: No such file or directory
#include "NodeSettings.h"
^~~~~~~~~~~~~~~~
compilation terminated.
```

Our team will investigate it and will get back to you soon. We are sorry for any inconvenience caused.

Thank you.

**Comment by cryptokatz** [comment]
The build process on the OS appears to be case sensitive as the file exists but the filename is in lowercase. Changed all references to lowercase.

**Comment by stanec** [comment]
I confirm the bug is fixed. Thanks a lot!
